SYMBOL = 'MATIC/USDT'
CURRENCY = 'USDT'
TIME_FRAME = '3m'
MARGIN = 15
LIMIT = 52

MARKET = 'MARKET'
MARK_PRICE = 'MARK_PRICE'
TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
STOP_MARKET = 'STOP_MARKET'
MARK_PRICE = 'MARK_PRICE'
SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'
BOTH = 'BOTH'
GTE_GTC = 'GTE_GTC'

HOLD = 'HODL'
CLOSE_INDEX = 4
COLUMNS = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

FAST_EMA_PERIOD = 13
MEDIUM_EMA_PERIOD = 40
SLOW_EMA_PERIOD = 90

MIN_MACD_DIFF = 0.0001

MAX_STOCH_RSI = 70
MIN_STOCH_RSI = 30

TREND_SMA_PERIOD = 200
ENABLE_TRAILING_STOP_LOSS = False

ENABLE_STOP_LIMITS = True
ENABLE_TAKE_PROFIT = True
ENABLE_STOP_LOSS = True
MAX_TAKE_PROFIT_MARGIN = 3
MAX_STOP_LOSS_MARGIN = 1.5

MACD_CROSSOVER_STRATEGY = "MACD_CROSSOVER_STRATEGY"
PARABOLIC_SAR_STRATEGY = "PARABOLIC_SAR_STRATEGY"
EMA_CROSSOVER_STRATEGY = "EMA_CROSSOVER_STRATEGY"
SEVEN_BAR_STRATEGY = "SEVEN_BAR_STRATEGY"
STRATEGY = SEVEN_BAR_STRATEGY
