SYMBOL = 'BTC/USDT'
CURRENCY = 'USDT'
TIME_FRAME = '15m'
CANDLESTICK_LIMIT = 500

MARGIN = 20
MAX_AMOUNT = 0.02

CALCULATION_DECIMAL_PLACES = 4
PRICE_DECIMAL_PLACES = 2
AMOUNT_DECIMAL_PLACES = 3

CURRENT_DF_INDEX = CANDLESTICK_LIMIT - 2
LAST_N_ROWS = 8

MARKET = 'MARKET'
MARK_PRICE = 'MARK_PRICE'
TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
STOP_MARKET = 'STOP_MARKET'
MARK_PRICE = 'MARK_PRICE'
SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'
BOTH = 'BOTH'
GTE_GTC = 'GTE_GTC'

CLOSE_LONG = 'CLOSE_LONG'
CLOSE_SHORT = 'CLOSE_SHORT'

HOLD = 'HODL'
CLOSE_INDEX = 4
COLUMNS = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

FAST_EMA_PERIOD = 21
MEDIUM_EMA_PERIOD = 40
SLOW_EMA_PERIOD = 90

MAX_STOCH_RSI = 75
MIN_STOCH_RSI = 25

TREND_SMA_PERIOD = 200
ENABLE_TRAILING_STOP_LOSS = False

ENABLE_STOP_LIMITS = True
ENABLE_TAKE_PROFIT = True
ENABLE_STOP_LOSS = True
MAX_TAKE_PROFIT_MARGIN = 2.5
MAX_STOP_LOSS_MARGIN = 2.5

SEVEN_BAR_STRATEGY = "SEVEN_BAR_STRATEGY"
STOCH_RSI_STRATEGY = "STOCH_RSI_STRATEGY"
STRATEGY = STOCH_RSI_STRATEGY

CLOSE_MESSAGE = {
    CLOSE_LONG: 'Closed Long Position',
    CLOSE_SHORT: 'Closed Short Position'
}
