SYMBOL = 'MATIC/USDT'
CURRENCY = 'USDT'
TIME_FRAME = '5m'
MARGIN = 15

MARKET = 'MARKET'
MARK_PRICE = 'MARK_PRICE'
TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET'
STOP_MARKET = 'STOP_MARKET'
MARK_PRICE = 'MARK_PRICE'
SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'
BOTH = 'BOTH'
GTE_GTC = 'GTE_GTC'

HOLD = 'HODL'
CLOSE_INDEX = 4
COLUMNS = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

FAST_EMA_PERIOD = 8
MEDIUM_EMA_PERIOD = 14
SLOW_EMA_PERIOD = 50

TREND_SMA_PERIOD = 8
ENABLE_TRAILING_STOP_LOSS = False

ENABLE_STOP_LIMITS = True
ENABLE_TAKE_PROFIT = False
ENABLE_STOP_LOSS = True
MAX_TAKE_PROFIT_MARGIN = 3
MAX_STOP_LOSS_MARGIN = 2

MACD_CROSSOVER_STRATEGY = "MACD_CROSSOVER_STRATEGY"
PARABOLIC_SAR_STRATEGY = "PARABOLIC_SAR_STRATEGY"
STRATEGY = PARABOLIC_SAR_STRATEGY
